config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :catagories, only:[:index,:show,:new,:create,:splash_screen] do 
     resources :payments, only: [:new,:create]
  end
  # Defines the root path route ("/")
  unauthenticated do
    root "catagories#splash_screen"
  end
    authenticated :user do
      root 'catagories#index', as: :authenticated_root
    end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :splash_screen, Catagory
    return unless user.present?

    can :manage, Catagory, author: user
    can :manage, Payment, author: user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :payments

  validates :name, presence: true, length: { in: 3..25 }
  validates :icon, presence: true
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :payments

  validates :name, presence: true, length: { in: 3..25 }
  validates :amount, presence: true, numericality: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :payments, foreign_key: 'author_id'
  has_many :catagories, foreign_key: 'author_id'
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, presence: true, length: { in: 3..50 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery prepend: true
  before_action :update_allowed_parameters, if: :devise_controller?
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden }
      format.html { redirect_to root_path, alert: exception.message }
    end
  end

  protected

  def after_sign_up_path_for(_resource_or_scope)
    root_url
  end

  def after_sign_out_path_for(_resource_or_scope)
    root_url
  end

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :email, :password, :current_password)
    end
  end
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
  load_and_authorize_resource
  def splash_screen; end

  def index
    @user = current_user
    @catagories = @user.catagories.includes(:payments)
  end

  def show
    @catagory = Catagory.find(params[:id])
    @payments = @catagory.payments.order('created_at desc')
    puts @payments.length
  end

  def new
    @catagory = Catagory.new
  end

  def create
    @catagory = Catagory.new(catagory_params)
    @catagory.author = current_user
    if @catagory.save
      redirect_to catagories_url, notice: 'Category has been created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def catagory_params
    params.require(:catagory).permit(:name, :icon, :payment_id)
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  load_and_authorize_resource
  def new
    @payment = Payment.new
    @catagory = Catagory.find(params[:catagory_id])
  end

  def create
    payment = Payment.find_by(id: params[:payment][:id]) if params[:payment][:id]
    payment = Payment.new(payment_params) unless params[:payment][:id]
    @payment = payment if payment.present?
    @payment = Payment.new(author: current_user) unless payment.present?
    @payment.author = current_user
    @catagory = Catagory.find(params[:catagory_id])
    if @payment.save
      @catagory.payments << @payment
      redirect_to catagory_url(@catagory), notice: 'Transaction has been created successfully.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def payment_params
    params.require(:payment).permit(:name, :amount, :id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catagories/_catagory.html.erb
<section class="w-100 bg-white pa3 flex items-center" style="gap:1rem">
	<img class="w-25 w-20-m w-10-ns" alt="category image" src="<%=catagory.icon%>">
	<p class="f5" style="flex:1.5"><%=catagory.name%></p>
	<p class="f5 fw6" style="flex:0"><%="$#{catagory.payments.sum(:amount)}"%></p>
</section>	

app/views/catagories/_header.html.erb
<header class="w-100 flex justify-between items-center pa2 pl1 pr1" id="header-login">
	<span><i class="fa fa-bars" aria-hidden="true"></i></span>
	<p class="f4 login-title">CATEGORIES</p>
	<%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
	 class:'sign-out fw6' %>
</header>	

app/views/catagories/_header_for_new.html.erb
<header class="w-100 flex justify-between items-center pa2 pt1 pb1" id="header-login">
	<%=link_to root_path do %>
	     &#x2190;
	<%end%>
	<p class="f4 login-title">NEW CATEGORY</p>
	<%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
	 class:'sign-out fw6' %>
</header>	

app/views/catagories/_index_header.html.erb
<header class="w-100 flex justify-between items-center pa2 pl1 pr1" id="header-login">
	<span><i class="fa fa-bars" aria-hidden="true"></i></span>
	<p class="f4 login-title">CATEGORIES</p>
	<%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
	 class:'sign-out fw6' %>
</header>	

app/views/catagories/_payment.html.erb
<section class="w-100 bg-white pa3 flex items-center">
	<p class="f5" style="flex:2"><%=payment.name%></p>
	<p class="f5 fw6" style="flex:0"><%="$#{payment.amount}"%></p>
</section>

app/views/catagories/_show_header.html.erb
<header class="w-100 flex justify-between items-center pa2 pl1 pr1" id="header-login">
	<%=link_to root_path do %>
	     &#x2190;
	<%end%>
	<p class="f4 login-title">TRANSACTIONS</p>
	<%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
	 class:'sign-out fw6' %>
</header>	

app/views/catagories/index.html.erb
<section class="vh-100 flex flex-column items-center">
 <%= render 'index_header' %>
  <p class="f3 green tc fw6"><%= notice %></p>
  <p class="f3 red tc fw6"><%= alert %></p>
 <main class="w-100 pb3 flex flex-column" style="gap:1rem;flex:1">
    <p class="bg-white flex justify-between f4 pa3 fw6">
        <span class="o-50">Total categories amount</span>
        <span><%="$#{@catagories.joins(:payments).sum(:amount)}"%></span>
    </p>
 <%if @catagories.length.positive?%>  
 <% @catagories.each do |catagory| %>
    <%= link_to catagory_path(catagory) do %>
      <%=render catagory %>
    <%end%> 
 <%end%>
 <%end%>
</main>
 <div class='new-category pt3 pb3 w-100 flex justify-center'>
    <%=link_to new_catagory_path, class:'w-90 tc pa3 ba b--white' do%>
        <button class="f3 fw5">New category</button>
    <%end%>
 </div>	
</section>

app/views/catagories/new.html.erb
 <%= render 'header_for_new'%>
 <section class="flex flex-column items-center mt3" style="gap:1rem">
<p class="f3 fw6">Add Category</p>
<%=form_with(model: @catagory, url: catagories_url,html: {class: "flex flex-column items-center w-100"}) do |f| %>
  <% if @catagory.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@catagory.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
        <% @catagory.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field w-100 w-50-ns mb3">
    <%= f.text_field :name, autofocus: true, class:'w-100', placeholder:'Category name'%>
  </div>

  <div class="field w-100 w-50-ns mb3">
    <%= f.text_field :icon,class:'w-100', placeholder:'Icon URL'%>
  </div>
  <div>
    <%= f.submit :Save, class:'submit-new-cat-trans tc pa4 pb2 pt2 fw6' %>
  </div>  
<% end %>

app/views/catagories/show.html.erb
<section class="vh-100 flex flex-column items-center">
 <%= render 'show_header' %>
  <p class="f3 green tc fw6"><%= notice %></p>
  <p class="f3 red tc fw6"><%= alert %></p>
 <main class="w-100 pb3 flex flex-column" style="gap:1rem;flex:1">
    <p class="bg-white flex justify-between f4 pa3 fw6">
        <span class="o-50">Total transactions amount</span>
        <span><%="$#{@catagory.payments.sum(:amount)}"%></span>
    </p>
 <%if @payments.length.positive?%>  
 <% @payments.each do |payment| %>
     <%=render partial: 'payment', locals:{payment:payment} %>
 <%end%>
 <%end%>
</main>
 <div class='new-transaction pt3 pb3 w-100 flex justify-center'>
    <%=link_to new_catagory_payment_path(@catagory), class:'w-90 tc pa3 ba b--white' do%>
        <button class="f3 fw5">New transaction</button>
    <%end%>
 </div>	
</section>

app/views/catagories/splash_screen.html.erb
<div class="splash-section">
  <p class="f3 green tc fw6 absolute"><%= notice %></p>
  <p class="f3 red tc fw6 absolute"><%= alert %></p>
<main class="w-100 center flex flex-column vh-100 items-center">
  <h1 class="tc" id='app-name'>Budget Calculator</h1>
  <div class="w-100" id="log-in">
  <%= link_to new_user_session_path, class:'w-100 pl2 pr2 pl6-ns pr6-ns pl5-m pr5-m' do%>
    <button class="w-100">LOG IN</button>
  <%end%>
 </div>
 <div id='sign-up'>
  <%= link_to new_user_registration_path do%>
    <button>SIGN UP</button>
  <%end%>
 </div> 	
</main>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="image" property="og:image" content="https://i.postimg.cc/SKSvdKQ6/glacial-lake-16247-herokuapp-com.png">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/payments/_header_for_new.html.erb
<header class="w-100 flex justify-between items-center pa2 pt1 pb1" id="header-login">
	<%=link_to catagory_path(@catagory) do %>
	     &#x2190;
	<%end%>
	<p class="f4 login-title">NEW TRANSACTION</p>
	<%= button_to 'Sign Out', destroy_user_session_path, method: :delete,
	 class:'sign-out fw6' %>
</header>	

app/views/payments/new.html.erb
 <%= render 'header_for_new'%>
 <section class="flex flex-column items-center mt3" style="gap:1rem">
<%=form_with(model: @payment, url: catagory_payments_url(@catagory),html: {class: "flex flex-column items-center w-100"}) do |f| %>
<p class="f3 fw6">Add transaction</p>
  <% if @payment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>
      <ul>
        <% @payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field w-100 w-50-ns mb3">
    <%= f.text_field :name, autofocus: true, class:'w-100', placeholder:'Transaction name'%>
  </div>

  <div class="field w-100 w-50-ns mb3">
    <%= f.text_field :amount,class:'w-100', placeholder:'Amount'%>
  </div>
  <div>
    <%= f.submit :Save, class:'submit-new-cat-trans tc pa4 pb2 pt2 fw6', id:'submit-new' %>
  </div>  
<% end %>

<hr class="w-80 w-30-ns ma3 pl0 pr0" style="height: 2px;background: #3778c2;">

<%=form_with(model:@payment, url: catagory_payments_url(@catagory),
html: {class: "flex flex-column items-center w-100"}) do |f| %>
<p class="f3 fw6">Add existing transaction</p>
  <div class="field w-100 w-50-ns mb3">
    <%= f.collection_select 'id', 
    current_user.payments.where.not(payments:@catagory.payments).order('created_at desc'), 
    :id, :name, {include_blank:true}, { class: "w-100" } %>
  </div>
  <div>
    <%= f.submit :Save, class:'submit-new-cat-trans tc pa4 pb2 pt2 fw6', id:'submit-existing' %>
  </div>  
<% end %>
</section>